### PR TITLE
Fix broken database tests

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@samtstern Ouch, we forgot to update the database tests after making some braking changes in the `FirebaseArray`s. This PR incorporates the updated `FirebaseArray`s and also ensures the tests pass.

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX I just noticed this the other day and thought "I must be crazy, my git is out of date" and shook it off.

Here's the real question (before I merge this): Why isn't Travis complaining?

**Comment by SUPERCILEX** [comment]
@samtstern lol, I had almost the same reaction! 😄 This was a decision by @puf to make the build faster: running the database tests requires booting up an emulator since they aren't unit tests... We could make them run on every Travis build, but it would slow things down significantly.

**Comment by samtstern** [comment]
@SUPERCILEX can we at least make the tests compile on each build?

**Comment by SUPERCILEX** [comment]
@samtstern Yup, I found the task.

**Pull request merged**
