### PR TITLE
Fix NoClassDefFoundErrors logspam for missing providers

### PR DESCRIPTION
**Pull request by wojtek-kalicinski**
This moves the optional SDK callback implementations to inner classes, to prevent NoClassDefFoundErrors in logcat when ART verifies the outer classes.

Fixes issue #1200

### CODE REVIEW

**Comment by samtstern** [comment]
Thanks @wojtek-kalicinski this makes a lot of sense.  However we've got a PR going that totally removes the `Provider` class anyway, to replace it with something better.  So I probably won't merge this as-is, but we'll make sure that the new classes don't directly inherit from any Facebook/Twitter classes.

@SUPERCILEX can you work this into your PR?

**Comment by wojtek-kalicinski** [comment]
Sounds good, thanks Sam!

**Comment by SUPERCILEX** [comment]
Yeah, I can totally do that. However, I'd like to see some logcat errors: is it crashing? What do you mean by "spammed with NCDEs?" I have trouble seeing how we'll get those errors if we never load the provider classes...

**Comment by wojtek-kalicinski** [comment]
It's not crashing, as the classes are not loaded. But before that, ART tries to verify them eagerly and just logs all these ncdf errors and stack traces (I'm not at my computer now so can't paste them).
It's just super annoying for development seeing this every time, not sure if it has actual performance impact, but it's better to avoid verification errors in any case.

**Comment by SUPERCILEX** [comment]
Oh gotya, here's the stack trace:
```

03-22 23:35:27.252 32592-32592/com.firebase.uidemo I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.firebase.ui.auth.data.remote.FacebookSignInHandler>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookCallback;
03-22 23:35:27.253 32592-32592/com.firebase.uidemo I/zygote:     at android.content.Intent com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.createIntent(android.content.Context, com.firebase.ui.auth.data.model.FlowParameters) (AuthMethodPickerActivity.java:66)
03-22 23:35:27.253 32592-32592/com.firebase.uidemo I/zygote:     at void com.firebase.ui.auth.util.signincontainer.SignInDelegate.startAuthMethodChoice() (SignInDelegate.java:290)
03-22 23:35:27.253 32592-32592/com.firebase.uidemo I/zygote:     at void com.firebase.ui.auth.util.signincontainer.SignInDelegate.onComplete(com.google.android.gms.tasks.Task) (SignInDelegate.java:174)
03-22 23:35:27.254 32592-32592/com.firebase.uidemo I/zygote:     at void com.google.android.gms.tasks.zzf.run() ((null):-1)
03-22 23:35:27.254 32592-32592/com.firebase.uidemo I/zygote:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:789)
03-22 23:35:27.254 32592-32592/com.firebase.uidemo I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
03-22 23:35:27.254 32592-32592/com.firebase.uidemo I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
03-22 23:35:27.254 32592-32592/com.firebase.uidemo I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
03-22 23:35:27.255 32592-32592/com.firebase.uidemo I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-22 23:35:27.255 32592-32592/com.firebase.uidemo I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
03-22 23:35:27.255 32592-32592/com.firebase.uidemo I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
03-22 23:35:27.255 32592-32592/com.firebase.uidemo I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookCallback" on path: DexPathList[[zip file "/data/app/com.firebase.uidemo-g1xEpphJo4K4RUKqccR2XA==/base.apk"],nativeLibraryDirectories=[/data/app/com.firebase.uidemo-g1xEpphJo4K4RUKqccR2XA==/lib/x86, /system/lib, /vendor/lib]]
03-22 23:35:27.255 32592-32592/com.firebase.uidemo I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
03-22 23:35:27.255 32592-32592/com.firebase.uidemo I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
03-22 23:35:27.255 32592-32592/com.firebase.uidemo I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at android.content.Intent com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.createIntent(android.content.Context, com.firebase.ui.auth.data.model.FlowParameters) (AuthMethodPickerActivity.java:66)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void com.firebase.ui.auth.util.signincontainer.SignInDelegate.startAuthMethodChoice() (SignInDelegate.java:290)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void com.firebase.ui.auth.util.signincontainer.SignInDelegate.onComplete(com.google.android.gms.tasks.Task) (SignInDelegate.java:174)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void com.google.android.gms.tasks.zzf.run() ((null):-1)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:789)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
03-22 23:35:27.256 32592-32592/com.firebase.uidemo I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
```

**Comment by SUPERCILEX** [comment]
Ohhhh, so you guys are pre-loading the classes to improve performance? `ClassLoader#loadClass(String)`? Anyway, fixed in https://github.com/SUPERCILEX/FirebaseUI-Android/commit/d111daadacf283d6818501a0c6b0dd571328e910.

**Comment by samtstern** [comment]
#1189 just went in so closing this, look out for `3.3.0` and thanks for flagging!

**Pull request closed without merging**
