### PR TITLE
fix snapshot gradle implementation typo

### PR DESCRIPTION
**Pull request by frapeti**
Hey there! So you want to contribute to FirebaseUI? Before you file this pull request, follow these steps:

  * Read [the contribution guidelines](CONTRIBUTING.md).
  * Run `./gradlew check` to ensure the Travis build passes.
  * If this has been discussed in an issue, make sure to mention the issue number here. If not, go file an issue about this to make sure this is a desirable change.
  * If this is a new feature please co-ordinate with someone on [FirebaseUI-iOS](https://github.com/firebase/firebaseui-ios) to make sure that we can implement this on both platforms and maintain feature parity.

### CODE REVIEW

**Comment by samtstern** [comment]
@frapeti thanks for this!  If you don't want to sign the CLA for a one-line change just let me know and I will make this change for you.

Worth noting that signing the CLA is a one-time thing for all Google repos though.

**Comment by frapeti** [comment]
@samtstern just signed the CLA 🙂

**Comment by samtstern** [comment]
Uhhh, seems like I just locked myself out of the house:
image

**Comment by samtstern** [comment]
@frapeti thanks for your help and patience!

**Pull request merged**
