### PR TITLE
Make shadows have buttons on pre-L devices.

### PR DESCRIPTION
**Pull request by samtstern**
See #842

**Before**

**After**

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Oh, just saw https://github.com/firebase/FirebaseUI-Android/issues/842#issuecomment-319514930. So yeah, awesome! 😄

**Comment by SUPERCILEX** [comment]
@samtstern ooooooooooh, actually I think we can add some gradients! This [StackOverflow post](https://stackoverflow.com/a/8722864/4548500) is for rounded corners but I think the same technique could apply. What do you think? 😀

**Comment by samtstern** [comment]
@SUPERCILEX nice, I will try something like that.

**Comment by samtstern** [comment]
@SUPERCILEX played with it for a little bit, none of the gradient types offered in XML drawables are suited for this.  Linear gradients band out from the center, and the radial and sweep gradients just don't offer enough configuration to look good on a big rectangle.

**Comment by SUPERCILEX** [comment]
@samtstern oh well, we tried. 😀

**Pull request merged**
