### PR TITLE
Add RestrictTo to all classes that need it

### PR DESCRIPTION
**Pull request by samtstern**
@SUPERCILEX making sure we have good coverage here and also making sure we can generate compatibility reports that ignore annotated classes.

### CODE REVIEW

**Comment by samtstern** [comment]
Also after we get this in I would like to cut and release `3.1.1`.  It's been a while since we had a release and we have some good bugfixes in there.

**Comment by SUPERCILEX** [comment]
@samtstern Yep, we definitely need a new release. 👍

As for the `RestrictTo` annotations, couldn't we put them on the package level to simplify things? I tried to make the entire `/data` package private for us, except for `FirebaseUiException` but that isn't public yet. (And we need a better package name for when we make it public anyway. 😄) Sadly, `/util` looks mixed.

What do you think?

**Comment by samtstern** [comment]
I think in an ideal world we'd put them at the package level but the class level gains us a few things:

- Less worrying about package boundaries
- Clearly visible when reading the source code
- Compatibility with the compliance checker tool

So for now I'd like to get it on all of the classes, even if it's redundant.

Looks like `FirebaseUiException` would be included if we released today.  Do you want that marked restricted?

**Comment by SUPERCILEX** [comment]
@samtstern SGTM about the package level annotations. And yeah, I think we should probably restrict `FirebaseUiException` since we haven't put enough thought into that API (and it's restricted in `IdpResponse`). Better safe than sorry! 😄

**Comment by samtstern** [comment]
Ok SGTM I will do that and then merge this.  Thanks for the input!

**Pull request merged**
