### PR TITLE
Bump SDK version to 10.2.0

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
This should contain the fix for #409

**Comment by SUPERCILEX** [comment]
OMG finally!!!!! Can't wait to check the new method count!!!

On a more serious note, do you think this concerns us?
> Improved the behavior of ID tokens with Smart Lock. Apps must now explicitly request a token by calling setIdTokenRequested(true). Also, apps can specify the audience and nonce values for a token using the setServerClientId() and setIdTokenNonce() methods.

**Comment by samtstern** [comment]
@SUPERCILEX nope we don't get ID tokens directly from SmartLock, although there's a strong argument that we should!

**Comment by SUPERCILEX** [comment]
@samtstern SGTM!

**Pull request merged**
