### PR TITLE
Dark mode fixes

### LINKED ISSUE #502: Wrong colors used in AuthUI when Night Mode enabled
* Android device: OnePlus 3
  * Android OS version: 7.0
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.0.1
  
#### Steps to reproduce:

  1. Set the default app theme as dark `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);`
  2. Try logging in via email
  
#### Observed Results:
  The TextColor in EditText was black 
#### Expected Results:
 The TextColor in EditText should be white, or a light color
#### Relevant Code:

screenshot_20170110-021308
screenshot_20170110-021258

### PR DESCRIPTION
**Pull request by the-dagger**
Fixes #502 
screenshot_20170113-005846
screenshot_20170110-023415

### CODE REVIEW

**Comment by samtstern** [comment]
There's still something wrong here. For example look at the check email screen. The label and hint text color are white on my Pixel:
the-dagger-pr

**Comment by the-dagger** [comment]
Hm, that's strange.
I'm using OnePlus 3 on Android 7.0 and it runs fine.
Hold on, I'll test it on an emulator as well

**Comment by samtstern** [comment]
@the-dagger did you ever figure this out, or should we close this PR for now?

**Comment by the-dagger** [comment]
Hey Sam,
I tried running it on various emulators and it worked fine for me.
I got a bit busy this week, so will give this a go again this weekend to
figure out what the issue was.

**Comment by samtstern** [comment]
@the-dagger it's been over a month since either of us updated this PR so I am going to close it in the name of housekeeping.  Please feel free to comment/re-open in the future if you ever come back to it!

**Pull request closed without merging**
