### PR TITLE
Password visibility toggle fix

### PR DESCRIPTION
**Pull request by SUPERCILEX**
This was a pain. In the end, I had to resort to just adding a workaround which sucks because the current implementation has a glitch where when you toggle visibility, the cursor position resets. Anyway, I created an AOSP issue for the desing lib: https://code.google.com/p/android/issues/detail?id=224914&thanks=224914&ts=1476159232

Back to the PR though, I upgraded gradle dependencies and removed appcompat-v7 which we weren't using. We're using the design lib. I also changed the style of two edittexts that should have been passwords.

#347

### CODE REVIEW

**Comment by samtstern** [comment]
This change LGTM.

@amandle what do you think?  Also I propose if we merge this we do a `0.6.1` release since the underlying Firebase dependency has changed.

**Comment by amandle** [comment]
LGTM, a `0.6.1` release makes sense to me

**Comment by samtstern** [comment]
0.6.1 released

**Comment by SUPERCILEX** [comment]
Awesome!

**Pull request merged**
