### PR TITLE
Offline Auth method picker

### PR DESCRIPTION
**Pull request by samtstern**
See #1585

### CODE REVIEW

**Comment by samtstern** [comment]
The idea here is to allow launching the auth method picker while offline in many cases.  If your app uses FirebaseUI as the "home" screen for new users this can be essential.

**Comment by samtstern** [comment]
@SUPERCILEX curious if you see any reasons to check for offline before showing the picker screen other than SmartLock?

**Comment by SUPERCILEX** [comment]
I'm actually curious, what happens if we don't do the check at all? `getActiveNetworkInfo()` is kind of a hack anyway since it will say you're connected even if the WiFi is behind a paywall or something like that (think Gogo Inflight).

It'll probably be hard to do, but I almost feel like each network request failure should be handled separately. We could map all the separate exceptions to a FUI network exception, similar to the user cancellation one. Then, we only fail when we truly couldn't connect to the network. It'll also improve the UX if a user was connected before the Smart Lock screen but then lost their internet juices.

In any case, I'm a fan of letting the user access the picker screen without an internet connection. 👍

**Comment by samtstern** [comment]
@SUPERCILEX good call, removing the offline check produces the same behavior (at the start of the flow).

Later in the flow some things go badly if we're offline:

- Email flow just basically does nothing.
- Google sign in flow hangs forever

We should handle all of this, as you said, but for now I just want to keep this change small and straighforward.

**Pull request merged**
