### PR TITLE
Version 2.0.1

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
As I believe we are working on a fix for the issues with the `11.0.0` SDK (rx incompatibility) I am going to hold this a day or two.  If no update comes I will release this on top of `11.0.0`.

**Comment by SUPERCILEX** [comment]
@samtstern SGTM!

**Comment by samtstern** [comment]
Ok travis has an error with the SDK license but given that the build passed before I updated to `11.0.1` and everything passes locally I am going to merge this over Travis' objections.

Never liked that Travis guy anyway.

**Comment by SUPERCILEX** [comment]
> Never liked that Travis guy anyway.

😆

Seriously though, same. I got so frustrated trying to get Travis happy with the preview build tools a while back that I said "Screw it!" and spent a day figuring out how to take control of my dependencies. Might as well get that going for FirebaseUI so I made #756.

**Pull request merged**
