### PR TITLE
Update Android Gradle plug-in to 2.1.2

### PR DESCRIPTION
**Pull request by friederbluemle**

### CODE REVIEW

**Comment by samtstern** [comment]
Thanks, merging!

**Comment by friederbluemle** [comment]
@samtstern Welcome.
Just curious: Are you not using the standard GitHub pull request merge mechanism? I noticed there was no merge commit created, and the merged commit hash (c13920f) is different from my original commit (4ad4f44), which results in me having to force-delete my local branch:

    error: The branch 'update-plugin' is not fully merged.

**Comment by samtstern** [comment]
@friederbluemle Github has a new "squash and merge" option that I have been using lately but I didn't realize it would cause pain for people submitting PRs.  I'll go back to using the standard method when I can, thanks for the notice.

**Comment by friederbluemle** [comment]
@samtstern Ah yes, I saw the new "squash and merge" option, and thought it might be related to that. It's definitely a useful feature, especially if there are lots of "fixup" and/or work-in-progress commits, and the PR submitter did not squash/rebase manually.
For pull requests with only a single commit, or a few commits that are independent from each other and logically structured, it might be better to use the regular "merge" option. It lets the submitter clearly see which commits went into the upstream repo, and allows him/her to cleanly delete their local branch.
Thanks! :+1:

**Pull request merged**
