### PR TITLE
Fix NPE when dismissing loading dialog (#985)

### PR DESCRIPTION
**Pull request by abdulwasae**
Issue #985

### CODE REVIEW

**Comment by abdulwasae** [comment]
I signed it!

**Comment by samtstern** [comment]
@abdulwasae thanks for the contribution!  Are you able to reproduce the NPE and prove that this fixes it?  If so could you provide some steps for me to try?

**Comment by abdulwasae** [comment]
@samtstern This does not happen always, but quite often. Steps that could reproduce this are as simple as using the phone verification feature again and again.

I have an app in production that utilises firebase phone verification, and a lot of the users are facing this NPE i posted above.

**Comment by samtstern** [comment]
@abdulwasae can't hurt!  I will merge this into the `3.1.1-dev` branch so it will be part of that release.  Thanks for contributing to FirebaseUI!

**Pull request merged**
