### PR TITLE
Upgrade to Firestore 16.0

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by samtstern** [comment]
Moved this to a `4.0.0` branch with the proper version number.  On the off chance anyone is using the `SNAPSHOT` builds it seems like the right thing to do.

**Comment by SUPERCILEX** [comment]
SGTM! Just to clarify, we're targeting everything at 4.0 now, right?

**Comment by samtstern** [comment]
Yep 3.4.0 is dead

**Comment by SUPERCILEX** [comment]
Sweet, do we want to kill the dev branch then?

**Comment by samtstern** [comment]
I'll delete it once 4.0.0 is out and we have no PRs against it anymore.

**Comment by SUPERCILEX** [comment]
Makes sense 👍

**Pull request merged**
