### PR TITLE
Attempt temporary fix

### LINKED ISSUE #1330: [Internal] Bintray uploading broken with new kts scripts
I am working on this, but filing it for good measure.  Here's what I see for the logs when trying to publish the `common` module:

```
> Task :common:bintrayUpload
Caching disabled for task ':common:bintrayUpload': Caching has not been enabled for the task
Task ':common:bintrayUpload' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Gradle Bintray Plugin version: 1.8.0
maven plugin was not applied, no pom will be uploaded.
Uploading to https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/com/firebaseui/common/4.0.1/common-4.0.1-javadoc.jar...
Uploaded to 'https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/com/firebaseui/common/4.0.1/common-4.0.1-javadoc.jar'.
Uploading to https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/com/firebaseui/common/4.0.1/common-4.0.1-sources.jar...
Uploaded to 'https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/com/firebaseui/common/4.0.1/common-4.0.1-sources.jar'.
Uploading to https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/com/firebaseui/common/4.0.1/common-4.0.1.aar...
Uploaded to 'https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/com/firebaseui/common/4.0.1/common-4.0.1.aar'.
Uploading to https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/value: com/firebaseui/value: firebase-ui-common/value: 4.0.1/value: firebase-ui-common-value: 4.0.1.aar...
Uploaded to 'https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/value: com/firebaseui/value: firebase-ui-common/value: 4.0.1/value: firebase-ui-common-value: 4.0.1.aar'.
Uploading to https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/value: com/firebaseui/value: firebase-ui-common/value: 4.0.1/value: firebase-ui-common-value: 4.0.1-javadoc.jar...
Uploaded to 'https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/value: com/firebaseui/value: firebase-ui-common/value: 4.0.1/value: firebase-ui-common-value: 4.0.1-javadoc.jar'.
Uploading to https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/value: com/firebaseui/value: firebase-ui-common/value: 4.0.1/value: firebase-ui-common-value: 4.0.1-sources.jar...
Uploaded to 'https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/value: com/firebaseui/value: firebase-ui-common/value: 4.0.1/value: firebase-ui-common-value: 4.0.1-sources.jar'.
Uploading to https://api.bintray.com/content/firebaseui/firebase-ui/firebase-ui-common/4.0.1/value: com/firebaseui/value: firebase-ui-common/value: 4.0.1/value: firebase-ui-common-value: 4.0.1.pom...
```

Then it fails.

I have added some logs to the setup and can't figure out what the `value` crap is:

```
Creating maven publication commonLibrary
        group: com.firebaseui
        artifact: firebase-ui-common
        version: 4.0.1
        aar: /usr/local/google/home/samstern/Projects/firebase/firebaseui-android/common/build/outputs/aar/common-release.aar
Bintray configuration for commonLibrary
        artifact: firebase-ui-common
        pub: commonLibrary
        config: archives
POM Transformation
        src: /usr/local/google/home/samstern/Projects/firebase/firebaseui-android/common/build/publications/commonLibrary/pom-default.xml
        dst: com/firebaseui/firebase-ui-common/4.0.1/
        name: firebase-ui-common-4.0.1.pom
```

### PR DESCRIPTION
**Pull request by samtstern**
#1330 

This also fails for the same reason though!  I am pulling my hair out.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@samtstern Does downgrading to Gradle 4.7 work? I know they changed stuff about publishing...

**Comment by samtstern** [comment]
@SUPERCILEX any ideas?  I am down to the point where I just want to roll back the gradle --> kotlin change but that would be sad.

**Comment by SUPERCILEX** [comment]
@samtstern Did you see my comment above? If we do downgrade to 4.7, we'll lose some DSL for the maven publishing so we'll have to go back to the `addNode` stuff, but I don't mind submitting a PR for that. Downgrading is the only thing that makes sense since you've gone back to `.gradle` files. Otherwise, I'll be damned.

**Comment by samtstern** [comment]
Ok let me try 4.7

**Comment by SUPERCILEX** [comment]
👍 Just make sure to use the `.gradle` version of the `publishing` block you have in this PR since the current `.kts` files won't compile with 4.7.

**Pull request merged**
