### PR TITLE
Version 3.2.0

### PR DESCRIPTION
**Pull request by samtstern**
This is the release PR for `3.2.0`.  Will probably merge Monday so as not to release-and-bail on a Friday afternoon.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Wait! Possible credentials bug, will explain in just a sec.

**Comment by samtstern** [comment]
@SUPERCILEX no problem, waiting till Monday anyway.  Excited/nervous though.

**Comment by SUPERCILEX** [comment]
@samtstern Phew, thank goodness! While I was testing my fix for https://github.com/firebase/FirebaseUI-Android/pull/1109#issuecomment-359118643, I uncovered a _**HUGE**_ bug: we crash on _**EVERY**_ sign-in! 😭😱 PRs incoming, but I completely forgot that the smart lock fragment has to be initialized _before_ we can save the creds otherwise `getActivity()` will be null. That's probably the cause of #856 and we can fix it in 3.2! (I still despise that fragment and will do my best to exterminate it into our new and lovely ViewModels, but still, it would be nice to fix #856 😁)

**Comment by samtstern** [comment]
@SUPERCILEX yikes sounds bad!  At least on my Pixel I can sign in without crashing, but maybe it has to do with different devices?

**Comment by SUPERCILEX** [comment]
@samtstern Can you create an email account?

**Comment by samtstern** [comment]
@SUPERCILEX yes I can although without the autofill override option I don't see a SmartLock save dialog when I do it.

**Comment by SUPERCILEX** [comment]
Huh, that's really weird. On the latest build, it crashes everytime I try to create an account:
```
01-19 16:41:36.926 17933-17933/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.firebase.uidemo, PID: 17933
                                                   java.lang.IllegalStateException: Can't save credentials in null Activity
                                                       at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish(SaveSmartLock.java:154)
                                                       at com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish(HelperActivityBase.java:103)
                                                       at com.firebase.ui.auth.ui.email.RegisterEmailFragment$3.onSuccess(RegisterEmailFragment.java:271)
                                                       at com.firebase.ui.auth.ui.email.RegisterEmailFragment$3.onSuccess(RegisterEmailFragment.java:267)
                                                       at com.google.android.gms.tasks.zzj.run(Unknown Source:27)
                                                       at android.os.Handler.handleCallback(Handler.java:790)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by samtstern** [comment]
@SUPERCILEX sounds like it's a race condition of some sort for when we call `getActivity()` in the smartlock fragment?  Maybe we should do it in `onActivityCreated`?

**Comment by SUPERCILEX** [comment]
Yup, see: https://github.com/firebase/FirebaseUI-Android/pull/1111#discussion_r162766738

**Comment by samtstern** [comment]
Rebased on top of #1111

**Comment by SUPERCILEX** [comment]
Another stopship (will work on it over lunch):
screenshot_20180122-114113

**Pull request merged**
