### PR TITLE
API Proposal for ensuring User's explicit acceptance for Tos/PP #1338

### PR DESCRIPTION
**Pull request by iamyaoxi**

### CODE REVIEW

**Comment by iamyaoxi** [comment]
Hmm.. Travis CI seems to give Translation-related error. How do I fix this?

**Comment by samtstern** [comment]
@iamyaoxi don't worry about the translation errors for now.  You can add `"MissingTranslation"` to the `lintOptions { disable .... } }` list in the `build.gradle.kts` file to get around it for now.

**Comment by samtstern** [comment]
@iamyaoxi also are you comfortable making the UI changes in this PR as well?  That way we can merge it all at once?  Looks like you already set up the strings, which is good.

**Comment by iamyaoxi** [comment]
Hmm. What happen to this PR? Is it automatically done by robot?

I dont think I made commit 275e74fb

**Comment by samtstern** [comment]
I was surprised to see those commits as well ... We certainly didn't edit
it on our side.  Make sure your Github account is secure!

**Comment by iamyaoxi** [comment]
I was thinking it might happen when I re-forked the repository. I was trying to resync my repo with the origin, but somehow keep failing. So I decided to just re-fork it.

**Comment by iamyaoxi** [comment]
I'll close it for now. And open another pull request.

**Pull request closed without merging**
