### PR TITLE
Fix Auth sample code for signing out

### PR DESCRIPTION
**Pull request by fanky10**

### CODE REVIEW

**Comment by fanky10** [comment]
I am the author.

**Comment by samtstern** [comment]
LGTM, thanks for the cleanup!

**Comment by samtstern** [comment]
Squashed and merged,

**Comment by write2dale** [comment]
Is there an option for   Anonymous...  firebase.auth.AnonymousAuthProvider.PROVIDER_ID, 
and does it  account linking, Link Multiple Auth Providers to an Account...  https://firebase.google.com/docs/auth/web/account-linking

**Pull request merged**
