### PR TITLE
Robolectic now supports api 25!

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Upgrade all our tests to target sdk 25.

Note: we're probably going to have to upgrade again soon because of a stopship (that wasn't stopped) on windows: https://github.com/robolectric/robolectric/issues/2814.

### CODE REVIEW

**Comment by samtstern** [comment]
Does this mean that Windows developers won't be able to run our tests?

**Comment by samtstern** [comment]
Yep SGTM, let's not merge it until all devs have a working solution for our
tests.

**Comment by SUPERCILEX** [comment]
The fix should be out tomorrow: https://github.com/robolectric/robolectric/issues/2814#issuecomment-270813048.

**Comment by SUPERCILEX** [comment]
@samtstern The new version of robolectric came out: https://github.com/robolectric/robolectric/releases/tag/robolectric-3.2.1.

**Comment by samtstern** [comment]
@SUPERCILEX thanks for tracking that.

**Pull request merged**
