### PR TITLE
Store options in FirebaseRecyclerAdapter

### PR DESCRIPTION
**Pull request by samtstern**
Fix issue #1707

### CODE REVIEW

**Comment by samtstern** [comment]
cc @PatilShreyas does this look good to you?

**Comment by PatilShreyas** [comment]
Yes @samtstern. Looks Good! 👍

**Comment by abhilashi** [comment]
@samtstern @PatilShreyas thanks much for the quick fix. When is 6.0.3 going to be released wide?

**Comment by samtstern** [comment]
@abhilashi can't promise a date but we're hoping to release it soon.  It will probably be `6.1.0` actually since we will have new features.

**Comment by abhilashi** [comment]
Thank you. Is 6.1.0 out yet? If not, what the best way to include this fix in my project in the meantime?

**Comment by samtstern** [comment]
@abhilashi not yet!  If you really want to try this today you can try [including a -SNAPSHOT](https://github.com/firebase/FirebaseUI-Android#snapshot-builds) build in your project.  It will be on the `6.0.3-SNAPSHOT` branch.

We are hoping to launch `6.1.0` soon, we're waiting on some changes that need to come to the Firebase console first.

**Pull request merged**
