### PR TITLE
 Upgrade dependencies + Android Gradle Plugin 3.0 support

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Built off of #974, fixes #883

@samtstern I hope you don't mind me taking over, but the AGP recently reached `rc1` and I'd like us to benefit from the perf improvements and other goodies. My B if you wanted to do that! 😊

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@samtstern I would also recommend [clearing the cache](https://travis-ci.org/firebase/FirebaseUI-Android/caches) while we're at it to start fresh.

**Comment by samtstern** [comment]
@SUPERCILEX thanks for raising this, I just did a few things:

- Merged `master` into `3.0.1`
- Merged `master` into my other PR
- Cleared the caches, as you suggest
- Updated my other PR

Let's continue this as a review on the other change!

**Comment by SUPERCILEX** [comment]
@samtstern Thanks! Are you sure you want to do a review on your PR? There are quite a few extra changes in this one... maybe I could pull in your commit or you do so with mine?

**Comment by samtstern** [comment]
@SUPERCILEX ok I will merge your changes into mine.

**Pull request merged**
