### PR TITLE
Remove unnecessary theme attributes in AndroidManifest.xml

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@samtstern I think the reason we were originally confused is because we have theme attributes in the manifest. However, these aren't used so they shouldn't be there to make it clearer that we use `configureTheme`.

Note: this change includes #495 to minimize merge conflicts so that should be merged first.

### CODE REVIEW

**Comment by samtstern** [comment]
I just merged #495, so I'll review this once Github gets the real diff figured out.

**Comment by SUPERCILEX** [comment]
SGTM, I'll merge in a bit.

**Comment by SUPERCILEX** [comment]
@samtstern merged!

**Comment by SUPERCILEX** [comment]
The default theme is used here if people don't set one: https://github.com/firebase/FirebaseUI-Android/blob/version-1.1.0-dev/auth/src/main/java/com/firebase/ui/auth/AuthUI.java#L516.

**Pull request merged**
