### PR TITLE
Kill SignInDelegate ☠️

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Built on top of #1188 and #1189.

### CODE REVIEW

**Comment by samtstern** [comment]
Will review this after the base PRs are in, but I think more PRs should have :skull_and_crossbones:  in the title

**Comment by samtstern** [comment]
@SUPERCILEX do you think this is something that should be in `3.3.0`?

**Comment by SUPERCILEX** [comment]
@samtstern For sure, I'd really like to kill all of our `setRetainInstance(true)` fragments. Permanently. 😈 Also, what's a measly few hundred LoC changed after we just plowed through 3265? 😆

**Comment by SUPERCILEX** [comment]
If this PR goes through, https://github.com/firebase/FirebaseUI-Android/issues/1057 and https://github.com/firebase/FirebaseUI-Android/issues/1181 should now be fully addressed.

**Comment by samtstern** [comment]
@SUPERCILEX the funny thing about killing all of the retained Fragment instances is that a `ViewModel` is secretly a retained Fragment.

So the wisdom on retained fragments is officially that they are too powerful for mere mortals, but the spellcasters in Mountain View can distill them down into useful amulets called ViewModels which can improve the life of us villagers :-)

Anyway ... this PR LGTM!  Gonna merge.

**Comment by SUPERCILEX** [comment]
Haha, that's really good! 😂

**Comment by samtstern** [comment]
@SUPERCILEX by the way, we can release `3.3.0` as soon as play services `12.0.1` comes out, which should be soon.  It contains some critical bugfixes and I wouldn't want to release on `12.0.0`

**Comment by SUPERCILEX** [comment]
Oh lol, I just made an update PR. I'll let it sit until 12.0.1 comes out then.

**Pull request merged**
