### PR TITLE
Update Firebase Versions

### PR DESCRIPTION
**Pull request by samtstern**
These changes look breaking but they're actually safe, the major version number was to escape the version-range hell created by the previous release.

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX I am getting some very strange mockito failures on all tests.  Fixing...

**Comment by samtstern** [comment]
Ok I have absolutely no idea what is going on.  And I don't actually think any of our tests were running before ...

**Comment by SUPERCILEX** [comment]
Huh, we are using a dynamic version for mockito so maybe try using a fixed one that we know works?

**Comment by samtstern** [comment]
Oh wait I know what it is.

This beauty definitely stopped working:

```java
    private static void injectMockFirebaseAuth(FirebaseApp app) {
        for (Field field : FirebaseAuth.class.getDeclaredFields()) {
            field.setAccessible(true);

            Object o;
            try {
                o = field.get(null);
            } catch (IllegalAccessException e) {
                throw new IllegalStateException(e);
            } catch (NullPointerException e) {
                continue;
            }

            Type genericType = field.getGenericType();
            if (o instanceof Map && genericType instanceof ParameterizedType) {
                Type[] parameterTypes = ((ParameterizedType) genericType).getActualTypeArguments();
                if (parameterTypes.length != 2 || parameterTypes[0] != String.class
                        || parameterTypes[1] != FirebaseAuth.class) {
                    continue;
                }

                //noinspection unchecked
                Map<String, FirebaseAuth> instances = (Map<String, FirebaseAuth>) o;

                FirebaseAuth.getInstance(app);
                for (String id : instances.keySet()) {
                    instances.put(id, mock(FirebaseAuth.class));
                }

                break;
            }
        }
```

**Comment by SUPERCILEX** [comment]
Ouch, so is FirebaseAuth storing instances of itself differently? Do you want me to take a look or are you good?

**Comment by samtstern** [comment]
I think I can figure it out.  I am now at the point where my tests are green in Android Studio but red on the command line ... man Android testing is a joke!

**Comment by SUPERCILEX** [comment]
Haha, it's usually the other way around for me. 😉 Fingers crossed 🤞, right? 😂

**Comment by samtstern** [comment]
Ok they are all failing like this:

```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
0 matchers expected, 1 recorded:
-> at com.firebase.ui.auth.testhelpers.TestHelper.injectMockFirebaseAuth(TestHelper.java:135)

This exception may occur if matchers are combined with raw values:
    //incorrect:
    someMethod(anyObject(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
    //correct:
    someMethod(anyObject(), eq("String by matcher"));

For more info see javadoc for Matchers class.
```

Here's the line it doesn't like in `TestHelper`:
```java
        FirebaseAuth mockAuth = FirebaseAuth.getInstance(app);
        when(mockAuth.setFirebaseUIVersion(anyString()))  // <----- THIS ONE
                .thenReturn(Tasks.<Void>forResult(null));
```

Any ideas

**Comment by SUPERCILEX** [comment]
Yup, as feared, the map is gone:
image

I'm looking into where it went.

**Comment by SUPERCILEX** [comment]
Well darn, there's a new `ComponentContainer` interface which means we have to mess with that instead.

**Comment by SUPERCILEX** [comment]
Alright, I think I got it.

**Comment by SUPERCILEX** [comment]
@samtstern Ok, so things aren't looking too pretty. After investigating for ages how we could inject auth into the `final ComponentContainer` implementation, I realized that we don't even need to do it anymore since the `setFirebaseUIVersion` method is wrapped in a try catch anyway. (So that means you should be able to nuke the entire `injectMockFirebaseAuth` method.) However, now I can't get FirebaseAuth to not be null... it's kinda hard to understand how the components are added with minified and obfuscated source code. 😢 To me it looks like the component providers should be coming from the manifest, but I'm not sure.

**Comment by samtstern** [comment]
Thanks for giving it a shot anyway.  I'll try and figure it out by
comparing the obfuscated code to the real source.

**Comment by samtstern** [comment]
@SUPERCILEX after looking at how `FirebaseAuth.getInstance(FirebaseApp)` works now, it's a lot more complicated and not something we really want to be messing with via reflection, especially since a lot of the things we will depend on are obfuscated.

I have put in a very simple (and temporary) hack to get tests to pass: a `protected static FirebaseAuth` variable on `AuthUI` that can be overridden for testing.

Given that we really need to ship 4.0 to make the deadline for GDPR, I am inclined to go ahead with this testing hack and fix it in the next release by doing better injection of `FirebaseAuth`.

**Comment by samtstern** [comment]
Wow squash and merge is very broken.

**Comment by SUPERCILEX** [comment]
@samtstern #1337 addresses the testing hacks.

**Pull request merged**
