### PR TITLE
Jfk additional material migrations

### PR DESCRIPTION
**Pull request by joknu1**
A continuation of the migration to Material Components

Material lib updated, third party lib for progress bar removed (#1907), and Dialogs updated.

I've tried this head on various brands and android version from 5 to 10 (I have no android 4), and I can no longer find any theme related problems that I can't override in my own extension of FirebaseUI theme.

I'm unsure about my `Merge pull request`commit in this PR, maybe that should be removed?

### CODE REVIEW

**Review by rosariopfernandes — APPROVED** [review]
@joknu1 This looks great! 😃 



> I'm unsure about my Merge pull requestcommit in this PR, maybe that should be removed?

Don't worry about it, commits are usually squashed when a PR is merged into the Firebase repos.

**Comment by samtstern** [comment]
@joknu1 thank you, this is great stuff! I'm going to merge this, what other changes do you think we need to make to complete the transition to Material?

**Comment by joknu1** [comment]
Haha @samtstern, I was going to ask you the same question!

I think maybe the theme related `readMe` file need to be reviewed (not completely sure though). Also test that the example themes from the demo app work as expected on all supported android versions. Even though Material should be backwards compatible, there's a lot of unexpected behavior on some API versions. However, I could not find any unsolvable problems for my app, that uses Firebase UI for Google/Facebook/Email login on Android 5 and higher.

Let me know what else I can do to make material branch ready for merge!

**Comment by samtstern** [comment]
@joknu1 thanks!  I think you're right that the README and the Sample App themes are probably up next. Even though it should be backwards compatible we'll want to make sure we document the latest.

I'll have to find some time next week to do more testing of my own

**Pull request merged**
