### PR TITLE
Fix broken POM files

### PR DESCRIPTION
**Pull request by SUPERCILEX**
See https://github.com/firebase/FirebaseUI-Android/issues/1060#issuecomment-352201278

The old POM file:
```xml
  <dependencies>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-auth</artifactId>
      <version>11.6.2</version>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-auth</artifactId>
      <version>11.6.2</version>
    </dependency>
  </dependencies>
```

The new POM file:
```xml
  <dependencies>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-auth</artifactId>
      <version>11.6.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-auth</artifactId>
      <version>11.6.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>design</artifactId>
      <version>27.0.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>customtabs</artifactId>
      <version>27.0.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support.constraint</groupId>
      <artifactId>constraint-layout</artifactId>
      <version>1.1.0-beta3</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>android.arch.lifecycle</groupId>
      <artifactId>extensions</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>cardview-v7</artifactId>
      <version>27.0.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-auth</artifactId>
      <version>11.6.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-auth</artifactId>
      <version>11.6.2</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>

```

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Oh wait, the compile deps are showing up twice.

**Comment by SUPERCILEX** [comment]
Ok, I think we're good:
```xml
  <dependencies>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-auth</artifactId>
      <version>11.6.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-auth</artifactId>
      <version>11.6.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>design</artifactId>
      <version>27.0.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>customtabs</artifactId>
      <version>27.0.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support.constraint</groupId>
      <artifactId>constraint-layout</artifactId>
      <version>1.1.0-beta3</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>android.arch.lifecycle</groupId>
      <artifactId>extensions</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>cardview-v7</artifactId>
      <version>27.0.2</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

**Comment by samtstern** [comment]
@SUPERCILEX thanks for trying for the quick fix but I think we're running in the wrong direction here.  The old POM, while causing problems, was working as intended.  Only things marked `api` should show up in the POM, things marked `implementation` should be exactly that: implementation details.

The problem here is we were only considering the deps we export in our Java API surface.  Because of how our resources/layouts get merged into the user's app though, any class we use in XML must also be an `api` dependency.

So let's fix this by marking the appropriate libs as `api` rather than moving anything that's `implementation` into the POM.

**Comment by samtstern** [comment]
Here are all the views we are effective exporting:

```bash
$ find . -path "*src*" -type f -name "*.xml" \
    | xargs grep -E -o -h "<[a-z0-9]+\.[a-zA-Z0-9\.]+" \
    | sort \
    | uniq
```

Result:
```
<android.support.constraint.Barrier
<android.support.constraint.ConstraintLayout
<android.support.design.widget.CoordinatorLayout
<android.support.design.widget.TextInputEditText
<android.support.design.widget.TextInputLayout
<android.support.v7.widget.CardView
<android.support.v7.widget.RecyclerView
<com.firebase.ui.auth.ui.phone.CountryListSpinner
<com.firebase.ui.auth.ui.phone.SpacedEditText
<com.firebase.ui.auth.util.ui.BaselineTextInputLayout
<com.firebase.ui.auth.util.ui.SupportVectorDrawablesButto
```

**Comment by SUPERCILEX** [comment]
@samtstern I'm pretty sure that's unnecessary—the POM scopes are supposed to handle `api`/`implementation`. See this SO answer that explains the POM runtime and compile scopes: https://stackoverflow.com/a/29230903/4548500

> **compile**
> 
> This is the default scope, used if none is specified. Compile dependencies are available in all classpaths of a project. _Furthermore, those dependencies are propagated to dependent projects._

> **runtime**
> 
> This scope indicates that the dependency is not required for compilation, but is for execution. _It is in the runtime and test classpaths, but not the compile classpath._

Just to make sure, I'll test it in a bit.

**Comment by samtstern** [comment]
Confirmed that your `runtime` POM dependencies make the app compile.  Gonna play with some more situations.

**Comment by SUPERCILEX** [comment]
Sweet! I'm also testing the provided deps so please hold off on merging if you're satisfied with the testing on your side. 😄

**Comment by samtstern** [comment]
Applying your POM fix to `3.1.2-SNAPSHOT` and using the `build.gradle` from the originally reported issue I see this dependency resolution:

```
debugRuntimeClasspath - Resolved configuration for runtime for variant: debug
+--- com.android.support:appcompat-v7:26.1.0 -> 27.0.2
|    +--- com.android.support:support-annotations:27.0.2
|    +--- com.android.support:support-core-utils:27.0.2
|    |    +--- com.android.support:support-annotations:27.0.2
|    |    \--- com.android.support:support-compat:27.0.2
|    |         +--- com.android.support:support-annotations:27.0.2
|    |         \--- android.arch.lifecycle:runtime:1.0.3
|    |              +--- android.arch.lifecycle:common:1.0.3
|    |              |    \--- com.android.support:support-annotations:26.1.0 -> 27.0.2
|    |              +--- android.arch.core:common:1.0.0
|    |              |    \--- com.android.support:support-annotations:26.1.0 -> 27.0.2
|    |              \--- com.android.support:support-annotations:26.1.0 -> 27.0.2
|    +--- com.android.support:support-fragment:27.0.2
|    |    +--- com.android.support:support-compat:27.0.2 (*)
|    |    +--- com.android.support:support-core-ui:27.0.2
|    |    |    +--- com.android.support:support-annotations:27.0.2
|    |    |    \--- com.android.support:support-compat:27.0.2 (*)
|    |    +--- com.android.support:support-core-utils:27.0.2 (*)
|    |    \--- com.android.support:support-annotations:27.0.2
|    +--- com.android.support:support-vector-drawable:27.0.2
|    |    +--- com.android.support:support-annotations:27.0.2
|    |    \--- com.android.support:support-compat:27.0.2 (*)
|    \--- com.android.support:animated-vector-drawable:27.0.2
|         +--- com.android.support:support-vector-drawable:27.0.2 (*)
|         \--- com.android.support:support-core-ui:27.0.2 (*)
+--- com.android.support.constraint:constraint-layout:1.0.2 -> 1.1.0-beta3
|    \--- com.android.support.constraint:constraint-layout-solver:1.1.0-beta3
\--- com.firebaseui:firebase-ui-auth:3.1.2-SNAPSHOT
     +--- com.google.firebase:firebase-auth:11.6.2
     |    +--- com.google.android.gms:play-services-base:11.6.2
     |    |    +--- com.google.android.gms:play-services-basement:11.6.2
     |    |    |    +--- com.android.support:support-v4:25.2.0 -> 27.0.2
     |    |    |    |    +--- com.android.support:support-compat:27.0.2 (*)
     |    |    |    |    +--- com.android.support:support-media-compat:27.0.2
     |    |    |    |    |    +--- com.android.support:support-annotations:27.0.2
     |    |    |    |    |    \--- com.android.support:support-compat:27.0.2 (*)
     |    |    |    |    +--- com.android.support:support-core-utils:27.0.2 (*)
     |    |    |    |    +--- com.android.support:support-core-ui:27.0.2 (*)
     |    |    |    |    \--- com.android.support:support-fragment:27.0.2 (*)
     |    |    |    \--- com.google.android.gms:play-services-basement-license:11.6.2
     |    |    +--- com.google.android.gms:play-services-tasks:11.6.2
     |    |    |    +--- com.google.android.gms:play-services-basement:11.6.2 (*)
     |    |    |    \--- com.google.android.gms:play-services-tasks-license:11.6.2
     |    |    \--- com.google.android.gms:play-services-base-license:11.6.2
     |    +--- com.google.android.gms:play-services-basement:11.6.2 (*)
     |    +--- com.google.firebase:firebase-common:11.6.2
     |    |    +--- com.google.android.gms:play-services-basement:11.6.2 (*)
     |    |    +--- com.google.android.gms:play-services-tasks:11.6.2 (*)
     |    |    \--- com.google.firebase:firebase-common-license:11.6.2
     |    +--- com.google.android.gms:play-services-tasks:11.6.2 (*)
     |    \--- com.google.firebase:firebase-auth-license:11.6.2
     +--- com.google.android.gms:play-services-auth:11.6.2
     |    +--- com.google.android.gms:play-services-auth-api-phone:11.6.2
     |    |    +--- com.google.android.gms:play-services-base:11.6.2 (*)
     |    |    +--- com.google.android.gms:play-services-basement:11.6.2 (*)
     |    |    +--- com.google.android.gms:play-services-tasks:11.6.2 (*)
     |    |    \--- com.google.android.gms:play-services-auth-api-phone-license:11.6.2
     |    +--- com.google.android.gms:play-services-auth-base:11.6.2
     |    |    +--- com.google.android.gms:play-services-base:11.6.2 (*)
     |    |    +--- com.google.android.gms:play-services-basement:11.6.2 (*)
     |    |    +--- com.google.android.gms:play-services-tasks:11.6.2 (*)
     |    |    \--- com.google.android.gms:play-services-auth-base-license:11.6.2
     |    +--- com.google.android.gms:play-services-base:11.6.2 (*)
     |    +--- com.google.android.gms:play-services-basement:11.6.2 (*)
     |    \--- com.google.android.gms:play-services-tasks:11.6.2 (*)
     +--- com.android.support:design:27.0.2
     |    +--- com.android.support:support-v4:27.0.2 (*)
     |    +--- com.android.support:appcompat-v7:27.0.2 (*)
     |    +--- com.android.support:recyclerview-v7:27.0.2
     |    |    +--- com.android.support:support-annotations:27.0.2
     |    |    +--- com.android.support:support-compat:27.0.2 (*)
     |    |    \--- com.android.support:support-core-ui:27.0.2 (*)
     |    \--- com.android.support:transition:27.0.2
     |         +--- com.android.support:support-annotations:27.0.2
     |         \--- com.android.support:support-compat:27.0.2 (*)
     +--- com.android.support:customtabs:27.0.2
     |    +--- com.android.support:support-compat:27.0.2 (*)
     |    \--- com.android.support:support-annotations:27.0.2
     +--- com.android.support.constraint:constraint-layout:1.1.0-beta3 (*)
     +--- android.arch.lifecycle:extensions:1.0.0
     |    +--- android.arch.lifecycle:runtime:1.0.3 (*)
     |    +--- android.arch.core:common:1.0.0 (*)
     |    +--- android.arch.core:runtime:1.0.0
     |    |    +--- com.android.support:support-annotations:26.1.0 -> 27.0.2
     |    |    \--- android.arch.core:common:1.0.0 (*)
     |    +--- com.android.support:support-fragment:26.1.0 -> 27.0.2 (*)
     |    \--- android.arch.lifecycle:common:1.0.3 (*)
     \--- com.android.support:cardview-v7:27.0.2
          \--- com.android.support:support-annotations:27.0.2
```

**Comment by SUPERCILEX** [comment]
And that's what we want, right? However, this PR doesn't seem to be doing quite what we'd expect as I've tested the following scenarios:
1. Use old version of CL: it's upgraded as expected
1. Don't include CL at all: compiles and still get code completion. Why??? It doesn't matter what scope I put, the CL dep is still added as a transitive one. I've tried everything, but I'm stuck: either the version isn't upgraded or it's added as a transitive dep which doesn't make sense. I feel like this is a bug in the Android Gradle Plugin, what do you think?
1. Use old version of Facebook dep: it _isn't_ upgraded for some reason, maybe a bug? That's the same behavior as before though.
1. Don't include Facebook dep: `ClassNotFoundException` as expected

What do you think, is this PR good to merge?

**Comment by samtstern** [comment]
> - Use old version of CL: it's upgraded as expected

Yep.

> - Don't include CL at all: compiles and still get code completion. Why??? It doesn't matter what scope I put, the CL dep is still added as a transitive one. I've tried everything, but I'm stuck: either the version isn't upgraded or it's added as a transitive dep which doesn't make sense. I feel like this is a bug in the Android Gradle Plugin, what do you think?

Yeah I find things like this all the time.  Gradle in general is compatible with maven repositories but does not implement Maven's exact dependency resolution.  I would not be surprised at all to find out that android just takes `runtime` deps and makes them `compile`.

> - Use old version of Facebook dep: it isn't upgraded for some reason, maybe a bug? That's the same behavior as before though.
> - Don't include Facebook dep: ClassNotFoundException as expected

Why would we expect Facebook to be upgraded?  I don't see it in the POM anywhere.

**Comment by samtstern** [comment]
Also worth nothing that this was our POM for version `3.0.0`:

```xml
 <dependencies>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>design</artifactId>
      <version>26.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>customtabs</artifactId>
      <version>26.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.android.support.constraint</groupId>
      <artifactId>constraint-layout</artifactId>
      <version>1.1.0-beta1</version>
    </dependency>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-auth</artifactId>
      <version>11.4.2</version>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-auth</artifactId>
      <version>11.4.2</version>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>cardview-v7</artifactId>
      <version>26.1.0</version>
    </dependency>
  </dependencies>
```

So we had deps on design, custom tabs, constraint-layout, and cardview in addition to the Firebase/Play deps.  We did not declare `scope` on any of them though.  And if we can't prove that `scope` does anything, I don't think we should add it.

**Comment by SUPERCILEX** [comment]
For facebook, I just added it in e7c29ef with the provided scope though that doesn't seem to have any effect. So yeah, we can remove it.

As for the `runtime` deps, how should we proceed? Removing them from the POM means we won't be updating the consumer's deps and could lead to those `isStateSaved` `NoSuchMethodError`s from the [EasyPermissions support lib thing](https://github.com/googlesamples/easypermissions/issues/184#issuecomment-350932728) or the CL stuff we saw here, but adding them means we leak the deps transitively which is the complete opposite of what the 3.0 Android Gradle Plugin is trying to do.

As for your scope concern, the default is `compile` which isn't what we want. I think we should keep the scopes in case that scope bug gets fixed.

Thoughts on how we should proceed?

**Comment by samtstern** [comment]
@SUPERCILEX ok I am fine to keep the scopes.  Let's remove the bit about the `provided` deps though, they've never been in the POM before and I don't want to add them now as the current check-at-runtime-throw-exception mechanism has generated no complaints.

**Comment by SUPERCILEX** [comment]
SGTM, see b36d746

**Pull request merged**
