### PR TITLE
Undo layout changes from #515

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
Fixes #521.

@puf  or @SUPERCILEX PTAL.  This will have to become `v1.1.1` since we broke people who don't use a logo (which means we broke the default).

**Comment by samtstern** [comment]
First build errored out due a Travis issue, but it passed on restart:
https://travis-ci.org/samtstern/FirebaseUI-Android

**Comment by SUPERCILEX** [comment]
@samtstern LGTM. Would you be ok with me trying to rewrite the auth picker layout using `ConstraintLayout`? It would let us use constraint biases meaning we don't need hard dp values making the layout more flexible. If not, I would still like to submit a PR making horizontal layouts usable by moving the buttons to the right of the logo.

PS: if you're cool with `ConstraintLayout`, I would like to slowly convert our codebase to use it thus minimizing nesting and improving performance. The original plan was to submit one massive PR converting everything to `ConstraintLayout`, but I don't think that's going to happen. Instead, we can go through it one layout at a time.

**Comment by samtstern** [comment]
@SUPERCILEX I do think in general ConstraintLayout is a great solution to this problem.  However in the interest of un-breaking people quickly I think this simple revert as 1.1.1 is the right thing to do (surprisingly we never got complaints in the past about the layout).

How do you feel about targeting fluid layouts for 1.2.0?

**Comment by SUPERCILEX** [comment]
@samtstern no no, I totally agree with you. Sorry for not making this clearer: I'm expecting the `ConstraintLayout` transition to be slow and drawn out so we can ensure quality and not mess stuff up. This PR should definitely be merged into the 1.1.1 release and the `ConstraintLayout` stuff my even be spread out into the 1.3.0 release depending on how quickly you want to get 1.2.0 out.

PS: I believe #375 is a complaint about landscape layout.

**Comment by samtstern** [comment]
@SUPERCILEX :+1:

**Pull request merged**
