### PR TITLE
Update and fix dependencies (cough cough, Facebook 😁)

### PR DESCRIPTION
**Pull request by SUPERCILEX**
See #926 

@samtstern I'm targeting `v2.3.1`... Do you still plan on releasing that? Or are we moving on to 3.0?

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX this is the correct branch, may try and get a `2.4.0` out, `2.3.1` would not be the right version anymore since we added some functionality (default phone number args)

**Comment by samtstern** [comment]
@SUPERCILEX what do we get by upgrading to `4.27.0`?

**Comment by SUPERCILEX** [comment]
@samtstern Oh, yeah gotya. 😄 

> What do we get by upgrading to `4.27.0`?

Besides some bug fixes, we mostly benefit from Facebook's new module system to reduce APK size, hence why they broke compatibility. I'm guessing you're think of pushing this to 3.0 since it breaks compatibility for people who don't update the Facebook lib?

**Comment by samtstern** [comment]
@SUPERCILEX does it break compatibility?  If someone consuming this specifies a lesser version Gradle will upgrade to ours.

**Comment by SUPERCILEX** [comment]
@samtstern Not anymore, right? We're using provided deps for the auth stuff:
https://github.com/firebase/FirebaseUI-Android/blob/9dc4c120f33d4f4acc42b2a0c2195e130e8b1076/auth/build.gradle#L54-L55

And I'm pretty sure our Gradle deps don't touch the consumer's because we're using `provided`.

**Comment by samtstern** [comment]
Ohhh yeah.  Well I think we can push this to 3.0.0 to be super-duper-safe.  Even though I bet it would be fine either way.

**Comment by SUPERCILEX** [comment]
@samtstern K, I changed the base to 3.0.

**Pull request merged**
