### PR TITLE
Fix phone verification progress dialog bugs on pre-L devices

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@samtstern The dialog looks like this pre-L:
image

Pretty gross, right? 😆 

Anyway, since `ProgressDialog` is deprecated in Android O and we have a layout that basically just recreates it, I've updated `CompletableProgressDialog` to be a plain old `DialogFragment` and it now looks like this pre-L:
image

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX you're on a roll today!  Won't be able to get to this one until Monday though.


cc @ashwinraghav

**Comment by SUPERCILEX** [comment]
@samtstern Haha, that was the last of it! 😄 SGTM!

**Comment by samtstern** [comment]
Ok since we have this fatal crash issue I am going to push this out to `2.1.2` rather than try to rush it for `2.1.1`.

**Comment by SUPERCILEX** [comment]
@samtstern SGTM

**Comment by samtstern** [comment]
Finally had time to check this, LGTM.  Thanks for tackling this!

**Comment by SUPERCILEX** [comment]
@samtstern No prob, glad to see it merged! 😄

**Pull request merged**
