### PR TITLE
Database tests, minor bugfix

### LINKED ISSUE #321: Move Database tests out of library dir and into database dir
Right now the tests for the Database module are under `library/`, they should be under `database/`

### PR DESCRIPTION
**Pull request by samtstern**
Due to the release of Play Services `9.6.0` we need a patch update to this library.

Also fixed #321 while I was at it.

### CODE REVIEW

**Comment by samtstern** [comment]
@puf please review

**Comment by samtstern** [comment]
@mcdonamp if you want me to skip 0.5.4 and go straight to 0.6.0 with basic storage stuff I could do that here too.

**Comment by mcdonamp** [comment]
@samtstern let's do 0.6.0 with basic storage stuff

**Comment by samtstern** [comment]
@mcdonamp updated

**Comment by samtstern** [comment]
Squashed and merged

**Pull request merged**
