### PR TITLE
Version 0.4.1

### PR DESCRIPTION
**Pull request by wolffcaleb**
Change-Id: I83e8d325e6775037f5ad500fe5bd03cbd012055c

### CODE REVIEW

**Comment by samtstern** [comment]
@wolffcaleb this pull request is slightly confusing to me.  I already see the 0.4.1 changes reflected in the master branch.  Do you not see the same?

**Comment by samtstern** [comment]
Going to close this, please re-open if I am misunderstanding something.

**Comment by wolffcaleb** [comment]
My apologies! I honestly am just trying to figure out Github. I was trying to get a piece of the code so I could test it and I figured a pull request would allow me to pull the code to my console. Could you explain to me how to utilize this code?
I would truly appreciate it!
Caleb

**Comment by samtstern** [comment]
@wolffcaleb ah I think this is just a terminology issue.  Pull Request is what you'd submit if you wanted to add a patch to this repository.

I think you want to clone the code, which you can do with `git clone https://github.com/firebase/FirebaseUI-Android`

**Comment by wolffcaleb** [comment]
Greatly appreciated! 
Thank you!
Caleb

**Pull request closed without merging**
