### PR TITLE
Fix startLogin being called on every configuration change with only one provider enabled

### PR DESCRIPTION
**Pull request by SUPERCILEX**
#549

### CODE REVIEW

**Comment by samtstern** [comment]
LGTM, but can you quickly explain how to reproduce the intial bug?  I didn't really understand the report in #549

**Comment by SUPERCILEX** [comment]
@samtstern Of course!

[Using a single provider with or without smart lock eventually calls `redirectToIdpSignIn`](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/util/signincontainer/SignInDelegate.java#L315) -> [an instance of `IdpSignInContainer` is created with `setRetainInstance(false)` (by default)](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/util/signincontainer/SignInDelegate.java#L329) -> [on every screen rotation, `startLogin` gets called](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/util/signincontainer/IdpSignInContainer.java#L119). The reason we don't see this bug anywhere else in FirebaseUI is because stuff like `AuthMethodPickerActivity` doesn't use `IdpSignInContainer`. `IdpSignInContainer`'s only usage is for `SignInDelegate`.

**Comment by SUPERCILEX** [comment]
@samtstern I just realized you might have been asking for a non-technical explanation for which the answer would be: start login with a single provider -> get to the provider's login section (eg not the smart lock thing) -> rotate the screen.

**Comment by samtstern** [comment]
@SUPERCILEX yep the second one was what I wanted, confirmed the bug.

**Comment by samtstern** [comment]
@SUPERCILEX https://travis-ci.org/firebase/FirebaseUI-Android looks like the build is failing with a lint error here but I don't get any on my machine.  Can you reproduce?

**Comment by SUPERCILEX** [comment]
@samtstern Travis says it's because support lib 25.1.1 came out https://developer.android.com/topic/libraries/support-library/revisions.html#25-1-1

I'll create an update PR later today since it's just bug fixes (and I'll also disable `GradleDependency` to make our builds less flaky like in #542).

**Pull request merged**
