### PR TITLE
Version 3.3.1

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX since there are no more open issues in the `3.3.1` milestone I am proposing to release `3.3.1` today and then we can move on to `3.4.0` development.  Sound good?

**Comment by SUPERCILEX** [comment]
Oh, too late 😆 Dunno if you released yet...

**Comment by GuanacoDevs** [comment]
@SUPERCILEX Sorry to ask, but this does not include the silent sign in yet?
It is scheduled for 3.4.0, right?

**Comment by SUPERCILEX** [comment]
@GuanacoDevs no, but 3.4 will. As for the support library not being updated, laziness? 😋 Feel free to bump up to 27.1.1.

**Pull request merged**
