### PR TITLE
Temporary fix issue #409

### PR DESCRIPTION
**Pull request by Akshit94**
https://github.com/firebase/FirebaseUI-Android/issues/409#issuecomment-267750540

Hey there! So you want to contribute to FirebaseUI? Before you file this pull request, follow these steps:

  * Read [the contribution guidelines](CONTRIBUTING.md).
  * If this has been discussed in an issue, make sure to mention the issue number here.  If not, go file an issue about this to make sure this is a desirable change.
  * If this is a new feature please co-ordinate with someone on [FirebaseUI-iOS](https://github.com/firebase/firebaseui-ios) to make sure that we can implement this on both platforms and maintain feature parity.

### CODE REVIEW

**Comment by Akshit94** [comment]
I signed it!

**Comment by SUPERCILEX** [comment]
@Akshit94 Thanks for your contribution! At the moment, FirebaseUI is undergoing a complete rewrite of all things email sign in. Because that, I created https://github.com/samtstern/FirebaseUI-Android/pull/4 to incorporate your changes in the new email flow making it easier for @samtstern to merge `v1.1.0-dev` into `master`. (No worries, I merged your changes so you still get credit! 😄)

PS: I also added your fix to `WelcomeBackPasswordPrompt` a different place where users sign in using email and password. 🎉

**Comment by Akshit94** [comment]
hey @SUPERCILEX thanku so much for letting me know...waiting eagerly for the next version...cheers man

**Comment by samtstern** [comment]
@Akshit94 there was some discussion on this in another PR, but I wanted to make sure to bring it back here.

First of all, thanks for submitting this fix.  I agree with you that in many cases this will fix issue #409.  However because the call to `reauthenticate` is done without waiting for the result, I believe this fix will not work 100% of the time and that could result in some frustration for developers (or bad user experiences).

If the `reauthenticate` call takes a while, the whole flow could finish before that call is completed.  This would mean #409 would reappear only in bad network conditions.  If the app relies on the issue being fixed, this could result in some crashes.

**Comment by Akshit94** [comment]
Hey @samstern nothing matters more than user experience so I totally understand the decision. Thanku so much for even considering the pull request and also so sorry for wasting your time..I think next time I will work more carefully and study the change under every condition before submitting a pull request..cheers🍻

**Comment by samtstern** [comment]
@Akshit94 not a waste of time at all!  We'll consider this technique as we do want to fix the bug, and if you think of a way to improve it yourself just update the PR.

**Comment by Akshit94** [comment]
@samtstern yeah sure👍

**Comment by samtstern** [comment]
Closing for now, based on previous discussion.

**Pull request closed without merging**
