### PR TITLE
Support Facebook Login without email

### PR DESCRIPTION
**Pull request by puilp0502**
Addresses #623.

I didn't know if I should bump up the version, so I left it as it is now.

### CODE REVIEW

**Comment by samtstern** [comment]
@puilp0502 just wanted to say I know this is lingering, I have been caught up on some other stuff and will test this soon.  Thank you for doing it!

**Comment by samtstern** [comment]
@puilp0502 FYI I changed the target branch to `version-2.0.0-dev` as that's where the next version will come from.  You may have to change your local setup a bit, let me know if that's confusing.

**Comment by samtstern** [comment]
Ok I just went and got a new phone number (thanks Google Voice) and then made a Facebook account that has no email.  Then I signed in and got the following (see below).

I am surprised that signing in like that even works!  I guess email is not a hard requirement for Facebook accounts (learn something new about your own products every day haha).

I am fine to merge this change, but @amandle can you chime in and let me know if this could cause any potential problems?

screenshot from 2017-03-09 12 02 03

no_email

**Comment by amandle** [comment]
LGTM, Twitter also doesn't require email be shared, so I don't foresee this change causing problems

**Pull request merged**
