### PR TITLE
Add opensource project config file

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX I think you'll like this sneak peek.  For our Firebase hack week I worked on (with some teammates) generating beautiful home pages for our open source repos.   By adding this config file, we get:

https://firebaseopensource.com/projects/firebase/firebaseui-android

Very much WIP.

**Comment by SUPERCILEX** [comment]
@samtstern Google javadoc themed READMEs? Love it! 😄 Does it work for any repo with a `project.json`?

**Comment by samtstern** [comment]
@SUPERCILEX there's also a backend service that turns the READMEs into HTML like this, so it has to be configured.

**Comment by SUPERCILEX** [comment]
Awwww... still, super cool!

**Pull request merged**
