### PR TITLE
Use recommended Robolectric setup for gradle plugin 3.0

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Built on top of #1070.

This also fixes some `ClassNotFoundError`s on Windows

Documentation: http://robolectric.org/getting-started/

### CODE REVIEW

**Comment by samtstern** [comment]
Looks like we have some test failures...

**Comment by SUPERCILEX** [comment]
@samtstern Looks like I forgot to merge my test fixes properly. 😄

**Comment by samtstern** [comment]
@SUPERCILEX LGTM!  Honestly Robolectric is still kind of dark magic to me but removing code and keeping things green == good.

**Comment by SUPERCILEX** [comment]
Haha, same here. I just stumbled upon some docs saying we didn't need the `@Config` anymore.

**Pull request merged**
