### PR TITLE
Fix IllegalArgumentException when submitting confirmation code

### PR DESCRIPTION
**Pull request by samtstern**
Issue #922

### CODE REVIEW

**Comment by samtstern** [comment]
cc @ashwinraghav @jstimes

**Comment by jstimes** [comment]
Is there a reason mVerificationId is not saved in onSaveInstanceState (in PhoneVerificationActivity)?

If a user leaves the app to look at the verification code then reopens it, onStart gets called and mVerificationId will be null until the onCodeSent callback gets fired. 

I agree that the null checks will prevent these crashes... just want to double-check that not saving mVerificationId is intentional.

**Comment by samtstern** [comment]
@jstimes well that callback is re-entrant so it's not supposed to be necessary to save the verification Id.  But clearly we need to protect against not getting the callback before submission.

@ashwinraghav is putting together a new PR.

**Comment by samtstern** [comment]
Closing in favor of #931

**Pull request closed without merging**
