### PR TITLE
Added setDefaultEmail for EmailBuilder

### PR DESCRIPTION
**Pull request by laurentiu-git**
Hey @samtstern !

I have implemented the feature for #1670 .

### CODE REVIEW

**Review by samtstern — COMMENTED** [review]
Two small changes:

1. Is there a test you could add for this to make sure that changing this setting results in the right flow?
2. Could you add an entry to `CHANGELOG.md`?

**Comment by laurentiu-git** [comment]
I will think about a test, and about `CHANGELOG.md`  it came in my mind after I did the pull request :)

**Comment by laurentiu-git** [comment]
Besides checking in `AuthUITest` that the value is stored inside `ExtraConstants.DEFAULT_EMAIL`, should I think of another way to test the flow? Perhaps inside the `EmailActivityTest` ?

**Comment by samtstern** [comment]
@laurentiu-git the ideal test would be one that checks the effect of the value, not just that the value is set.  So for example checking when the value is set and the user exists, the flow heads to the password screen not the email screen.

**Comment by samtstern** [comment]
@laurentiu-git these tests look great, thank you!  I'm going to resolve the merge conflicts (hope you don't mind) and then merge when CI is green.

**Comment by laurentiu-git** [comment]
While you are at it, I saw this test `testOnTroubleSigningIn_expectTroubleSigningInFragment`  being commented out and it appears that now it's working.

**Pull request merged**
