### PR TITLE
Allow flexible versions for transitive dependencies

### LINKED ISSUE #613: Support library version too low
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: All
  * Android OS version: All
  * Google Play Services version: 10.2.0
  * Firebase/Play Services SDK version: 10.2.0
  * FirebaseUI version: 1.2
  
### Step 3: Describe the problem:

Customtabs at version 25.1.1 while it should be
#### Steps to reproduce:

  1. Gradle Warns about the multiple version

  
#### Observed Results:

  Warning
  
#### Expected Results:

  Slow Downs
  
#### Relevant Code:

  ```
 
  ```

### PR DESCRIPTION
**Pull request by samtstern**
Should permanently fix #613 and similar by allowing any version greater than or equal to the one we depend on.

@CodingDoug check it out

### CODE REVIEW

**Comment by samtstern** [comment]
Makes the maven dependency declaration look like this:
```xml
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>customtabs</artifactId>
      <version>[25.1.1,)</version>
    </dependency>
```

Instead of this:
```xml
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>customtabs</artifactId>
      <version>25.1.1</version>
    </dependency>
```

**Comment by CodingDoug** [comment]
Yasss.

**Comment by samtstern** [comment]
@puf wdyt?  Is this a good idea?

@SUPERCILEX FYI

**Comment by samtstern** [comment]
Hmm this seems mildly evil.  I just tried this:

  * Make this version request `[25.1.0,)`
  * Make the app depend on `firebase-ui-auth:1.2.1` and `appcompat-v7:25.1.1`

Expected result:

  * All support dependencies resolve to `25.1.1`

Actual result:

  * All support dependencies resolved to `25.2.0`, the newest available

**Comment by SUPERCILEX** [comment]
@samtstern Have you seen the new [preview gradle plugin](http://tools.android.com/tech-docs/new-build-system/2-5-alpha-gradle-plugin)?

> New api, implementation, compileOnly and runtimeOnly configurations allow libraries to not always leak their dependencies to their consumers 

Maybe we can use that?

**Comment by samtstern** [comment]
Gonna take another swing at this but closing this one.

**Comment by samtstern** [comment]
Still experimenting, now dependency block looks like this.

Things to note:
  * Some deps are now provided (if the app will need them to use the library)
  * Support lib deps are allowed to move up to the next major version
  * Google / Firebase deps are allowed to move

```xml
  <dependencies>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>appcompat-v7</artifactId>
      <version>[25.3.0,26.0.0]</version>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>palette-v7</artifactId>
      <version>[25.3.0,26.0.0]</version>
    </dependency>
    <dependency>
      <groupId>com.github.bumptech.glide</groupId>
      <artifactId>glide</artifactId>
      <version>3.7.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-storage</artifactId>
      <version>10.2.1</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
```

**Comment by SUPERCILEX** [comment]
This would also fix #438! 😄 (I'm pretty sure we're not using any new apis from `10.x`)

**Comment by samtstern** [comment]
I've made some progress but the issue in this comment is too big to ignore:
https://github.com/firebase/FirebaseUI-Android/pull/621#issuecomment-284077070

I am asking around internally to figure out why in the world it would resolve like that.

**Comment by SUPERCILEX** [comment]
@samtstern Aw dang! 😭 I hope ​you figure it out though! 😁

**Comment by samtstern** [comment]
Made a new change that gives me the behavior I want!  But it's a bad hack...

Here's what the dep blocks look like now:

```
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-auth</artifactId>
      <version>10.2.1+</version>
    </dependency>
```

I am pretty sure it's not valid maven syntax, but gradle just eats it up and it does exactly what I want.

**Comment by samtstern** [comment]
I just tried about a trillion combinations:

```
    // COMPILES
    // Support v4 resolves to 24.0.0
    fooCompile 'com.google.android.gms:play-services-basement:10.2.1'

    // COMPILES
    // Support v4 resolves to 25.3.1
    barCompile 'com.google.android.gms:play-services-basement:10.2.1'
    barCompile 'com.android.support:support-v4:25.3.1'

    // COMPILES
    // Support v4 resolves to 24.2.1
    bazCompile 'com.firebaseui:firebase-ui-auth:1.0.0'

    // COMPILES
    // Support v4 resolves to 25.3.1
    quxCompile 'com.firebaseui:firebase-ui-auth:1.2.0'
    quxCompile 'com.android.support:support-v4:25.3.1'

    // DOES NOT COMPILE: Multiple dex files define Lcom/google/android/gms/common/api/zze;
    // Support v4 resolves to 24.2.1
    // Play services auth resolves to 9.8.0
    // Play services basement resolves to 10.2.1
    wooCompile 'com.firebaseui:firebase-ui-auth:1.0.0'
    wooCompile 'com.google.android.gms:play-services-drive:10.2.1'

    // COMPILES
    // Support v4 resolves to 24.2.1
    // Play services auth resolves to 10.2.1
    // Play services basement resolves to 10.2.1
    waaCompile 'com.firebaseui:firebase-ui-auth:1.0.0'
    waaCompile 'com.google.android.gms:play-services-auth:10.2.1'

    // COMPILES
    // Support v4 resolves to 25.3.0
    // Play services auth resolves to 10.2.1
    // Play services basement resolves to 10.2.1
    weeCompile 'com.firebaseui:firebase-ui-auth:2.0.0-SNAPSHOT'

    // COMPILES
    // Support v4 resolves to 25.3.0
    // Play services auth resolves to 10.2.4
    // Play services basement resolves to 10.2.4
    wiiCompile 'com.firebaseui:firebase-ui-auth:2.0.0-SNAPSHOT'
    wiiCompile 'com.google.android.gms:play-services-auth:10.2.4'

    // DOES NOT COMPILE: Attribute meta-data#android.support.VERSION ...
    // Support v4 resolves to 26.0.0-alpha1
    wuuCompile 'com.firebaseui:firebase-ui-auth:2.0.0-SNAPSHOT'
    wuuCompile 'com.android.support:support-v4:26.0.0-alpha1'

    // COMPILES (but should it?)
    // Support v4 resolves to 25.3.0
    // Play services auth resolves to 10.2.1
    // Play services basement resolves to 10.2.4
    wyyCompile 'com.firebaseui:firebase-ui-auth:2.0.0-SNAPSHOT'
    wyyCompile 'com.google.android.gms:play-services-basement:10.2.4'
```

**Comment by samtstern** [comment]
I got schooled on the gradle forums:
https://discuss.gradle.org/t/gradle-strange-dependency-resolution/22609

I think I finally understand what's going on.  People can use any version of `play-services-{foo}`, `firebase-{foo}` or `support-{foo}` that will compile.  If they pick one of the deps we directly depend on (like `play-services-auth`) then gradle handles this nicely.

The problem comes when they use a mixed version of a dep of our deps.  So for example if you directly depend on `play-services-base:1234` then gradle gets confused and you end up with `play-services-base:1234` and `play-service-auth:10.2.1` in your tree, which causes an explosion due to the way play services works.

So all I need to do is document exactly what our dependencies are.

**Comment by SUPERCILEX** [comment]
@samtstern Ohhhhhh, I wish I had understood the purpose of your PR sooner! 😕 I thought you wanted to let devs use any dependency version! Instead you want to let devs use a version `>=` to ours which I have documented before: https://github.com/firebase/FirebaseUI-Android/issues/414#issuecomment-262283040. Sorry for not being able to help out sooner, but I'm happy to document our deps! 😄

**Comment by samtstern** [comment]
Yeah `>=` for now.  It would be nice to let them use any older version but it's too hard to support folks who are mixing in old Play Services since they could be thinking SDK bugs are FirebaseUI bugs.

I'll handle the doc update for this one, thanks though!

**Comment by SUPERCILEX** [comment]
@samtstern Awesome!

**Pull request closed without merging**
