### PR TITLE
Update Support Library Version

### PR DESCRIPTION
**Pull request by majid-vaghari**
Support Library is updated to version 27.1.0 on February 2018 and I think FirebaseUI should update its dependency. In my current project updating support library results in "Unable to merge dex". Please upgrade and release a new version as soon as possible.

Hey there! So you want to contribute to FirebaseUI? Before you file this pull request, follow these steps:

  * Read [the contribution guidelines](CONTRIBUTING.md).
  * Run `./gradlew check` to ensure the Travis build passes.
  * If this has been discussed in an issue, make sure to mention the issue number here. If not, go file an issue about this to make sure this is a desirable change.
  * If this is a new feature please co-ordinate with someone on [FirebaseUI-iOS](https://github.com/firebase/firebaseui-ios) to make sure that we can implement this on both platforms and maintain feature parity.

### CODE REVIEW

**Comment by majid-vaghari** [comment]
I signed it!

**Comment by samtstern** [comment]
@majid-vaghari I will add this to the `3.3.0` release, thanks!

If you're having `dex` issues now, I am happy to help.

**Comment by majid-vaghari** [comment]
Thank you @samtstern. I changed the version of support library back to 27.0.2 in my own project. The problem seems to be originating from the fact that `firebase-ui-auth:3.2.2` depends on support library 27.0.2 so if my project has a dependency on both support library 27.1.0 and `firebase-ui-auth:3.2.2`, Gradle apparently cannot resolve them well. I tried to go around this by telling Gradle not to include support library when I'm specifying dependency on firebaseui. Something similar to this:
```gradle
dependencies {
    implementation 'com.android.support:design:27.1.0' // and some other packages from support library
    implementation ('com.firebaseui:firebase-ui-auth:3.2.2') {
        exclude group: 'com.android.support'
    }
}
```
But it didn't seem to work. Inevitably I downgraded the support library version back to 27.0.2 and the build process completed successfully.

If there is another workaround which you may know of, I would be glad to hear it from you.

**Comment by samtstern** [comment]
@majid-vaghari here's the general workaround:
https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies

So you'd want to add:

```groovy
implementation "com.android.support:design:27.1.0"
implementation "com.android.support:customtabs:27.1.0"
implementation "com.android.support:cardview-v7:27.1.0"
```

By explicitly adding those to your own `build.gradle` it tells gradle that you want to override the transitive dependency of `firebase-ui-auth`.

**Pull request merged**
