### PR TITLE
JavaDoc for paging adapter

### LINKED ISSUE #1287: Add documentation to paging builder
@samtstern Whoops, this one slipped us by. Do you want to take it?

### PR DESCRIPTION
**Pull request by samtstern**
Fixes #1287

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX thank you for finding all my lazy mistakes!  I/O brain.

**Comment by SUPERCILEX** [comment]
Haha, no problem, I'm still reeling from it too! 😂

**Comment by puf** [comment]
Wait? Were you there? How did I miss you? Why didn't Sam tell me? :-(

**Comment by SUPERCILEX** [comment]
@puf no, no, I wish! 😭 I meant reeling from all the announcements! 😁 I had conflicts this year, but #io19 will hopefully work out. 🙏🤞

**Comment by puf** [comment]
Cool. See you then/there!

**Pull request merged**
