### PR TITLE
Use lint to define what is public and what isn't

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@samtstern There have been multiple instances of people using non-public apis (#408, #490, and probably more) so I think we should define what is public and what isn't here. [Firebase Job Dispatcher](https://github.com/firebase/firebase-jobdispatcher-android/tree/master/jobdispatcher/src/main/java/com/firebase/jobdispatcher) took the approach of putting everything in one package and making it all package private. I really don't think that's a good idea since it makes developing the library difficult and confusing. Instead, we can use the `@RestrictTo` annotation from the support lib folks to get around this problem.

I've left the `provider` package public because it could theoretically be used out of FirebaseUI, but all of this is up to debate. I've also left some helpers public for the same reason. @samtstern what are your thoughts on this?

### CODE REVIEW

**Comment by samtstern** [comment]
Never knew about this!  That's pretty cool.  Can you add a screenshot showing what will happen in Android Studio if you try to use a restricted class?

**Comment by SUPERCILEX** [comment]
@samtstern Sadly, there isn't an inspection for this in Android Studio [yet](https://code.google.com/p/android/issues/detail?id=231481). However, lint will blow up on you if use a class marked with `@RestrictTo`: I found out about the annotation when we encountered that bug in the android gradle plugin alpha3 (https://github.com/samtstern/FirebaseUI-Android/pull/3#discussion_r92259692). So it will look like this if we run lint manually:

`@RestrictTo`:
image


`@VisisbleForTesting`:
image

**Comment by samtstern** [comment]
Looks great, thanks!

**Comment by goncalossilva** [comment]
> I've left the `provider` package public because it could theoretically be used out of FirebaseUI

This has been immensely helpful for us at Doist. Our UI flows are a bit different from what Firebase proposes, and it has been a great experience to be able to leverage all the work in the providers without having to use the UI bits as well. We hope this remains in the public API 😊

**Comment by samtstern** [comment]
@goncalossilva thanks for the feedback.  This change only affects lint so you can continue to ignore it, but it at least makes the division clear.  Do you have a public app that uses these modified flows?  I'd love to check it out.

**Comment by goncalossilva** [comment]
@samtstern It's currently in review, should be out in about 2/3 weeks, and will A/B test two different approaches. We'll let you know once it's out.

**Comment by pedrodanielcsantos** [comment]
@samtstern our work with the integration of FirebaseUI (the authentication module) where we're using the providers directly, as @goncalossilva said, was released yesterday, so in case you want to take a look the work we've done, you can check [Todoist](https://play.google.com/store/apps/details?id=com.todoist) 👍

**Comment by samtstern** [comment]
@pedrodanielcsantos thanks for the pointer, this is awesome!  I love Todoist, will download the update and take a look.

**Pull request merged**
