### PR TITLE
Spanish translation (auth and app)

### PR DESCRIPTION
**Pull request by javmarina**
This pull request includes Spanish translations for strings in the Firebase UI project. I have translated strings from Firebase UI Auth and the example app. This way, developers don't need to worry about translating library strings (like I did before).

### CODE REVIEW

**Comment by samtstern** [comment]
@javmarina thanks for this contribution!  Appreciate the effort here.  Since this is one of the languages we support on firebase.google.com (see #77) am inclined to merge, but we need a few things first:

@alfongj can you check out the Spanish here?
@morganchen12 how hard is it to port this to iOS?

**Comment by danielpassos** [comment]
@samtstern It's pretty simple to _port_ this to iOS. I'm going to send a PR there based on this one and another one for [mime](https://github.com/firebase/FirebaseUI-Android/pull/384)

**Comment by javmarina** [comment]
Any update on this??

**Comment by samtstern** [comment]
@javmarina sorry for the lack of updates here, we put off translations while working on the 1.0 release and are now back to discussing how to do them best.

**Comment by javmarina** [comment]
OK, thanks!

**Comment by javmarina** [comment]
When do you plan to add translations? I currently use my own in my projects but it's better to include them inside the library, available for every developer. I'm willing to translate the other strings (some of them have been added/modified).

**Comment by samtstern** [comment]
@javmarina I have decided to close translation pull requests.  They've been sitting around for a while and the silent, infinitely-open PR is not fair to you nor is it useful to us.  For now you should continue to maintain translations as part of your own app or as part of a library fork.

Eventually, we will get official translations for FirebaseUI for the major languages that Firebase supports.  When we go through that process, I will definitely provide the contents of this Pull Request as suggestions to the translators (there is a place in the system for that).

Thank you for taking the time to contribute!  We do appreciate it, even if we sometimes fail to demonstrate our appreciation.

**Comment by javmarina** [comment]
Don't worry about that. I understand the situation and am glad you explained it to me. This PR should be closed if it interferes with your current work. I just wanted to help developers but it is not an issue to maintain those strings on my own.

**Pull request closed without merging**
