### PR TITLE
Update to architecture components 1.0.0

### PR DESCRIPTION
**Pull request by samtstern**
cc @SUPERCILEX @CodingDoug

### CODE REVIEW

**Comment by CodingDoug** [comment]
When I tried this in my own sandbox, I got lint errors on code that was generated by the architecture components annotation processor.  Did that not happen here?

**Comment by SUPERCILEX** [comment]
Do you support Java 8? If so, you shouldn't be using the annotation processor because there's a interface with a bunch of empty defaults.

**Comment by CodingDoug** [comment]
Not sure what you mean.  I'm talking about this annotation processor:
    annotationProcessor "android.arch.lifecycle:compiler:$architectureVersion"

That generates code which ./gradlew check complains about.

**Comment by SUPERCILEX** [comment]
See https://developer.android.com/topic/libraries/architecture/adding-components.html.

```groovy
implementation "android.arch.lifecycle:common-java8:1.0.0"
```

**Comment by SUPERCILEX** [comment]
Oh, I see. No, I haven't seen that with FirebaseUI, sorry! 😊

**Comment by CodingDoug** [comment]
One other minor thing - there should be no need to include the runtime dependency here when using the extensions dependency.  extensions depends on runtime (which currently sits at 1.0.3).

**Pull request merged**
