### PR TITLE
Merge version-1.1.0-dev into master

### PR DESCRIPTION
**Pull request by samtstern**
Creating this PR in advance of QA.  Will discuss all 1.1.0 release or QA issues here.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@samtstern Whoa!!! There were more lines of code changed in this PR than [The Big Kahuna](https://github.com/firebase/FirebaseUI-Android/pull/390). 😄 (Also, all those red `X`s on each commit because of cla stuff look so scary 😨)

PS: could you merge #511 before finalizing QA (it removes the lint hack).

**Comment by SUPERCILEX** [comment]
@samtstern I also created #512 which fixes the broken documentation for `onDataChanged`.

**Comment by SUPERCILEX** [comment]
@samtstern Oh, wait I just noticed an issue.

**Comment by SUPERCILEX** [comment]
@samtstern Nevermind, I just noticed that the buttons in `AuthMenthodPickerActivity` are no longer positioned at the bottom of the layout leaving a lot of empty space. I don't think there is a way to solve that though since we are using a `ScrollView`.

**Comment by samtstern** [comment]
@SUPERCILEX yeah that's the one behavior change ... I think it's worth it to un-break landscape (and also help on very small devices) but if you think it's bad I am open to reverting the change.

**Comment by samtstern** [comment]
@puf @SUPERCILEX @mcdonamp @amandle I am going to do a merge/release at 3pm PST since I have found no issues in manual QA.  Respond here if you have some objection.

**Comment by SUPERCILEX** [comment]
@samtstern let's merge! :smile: And yeah, we should definitely keep the scroll view to make landscape layout bearable.

**Pull request merged**
