### PR TITLE
Don't ship our lint checks to consumers

### PR DESCRIPTION
**Pull request by SUPERCILEX**
It turns out `lintChecks` actually means give this check to people using the library... oops!

### CODE REVIEW

**Comment by samtstern** [comment]
```
com.firebase.ui.auth.ui.email.EmailActivityTest > testSignUpButton_validatesFields FAILED
    android.view.InflateException
        Caused by: android.view.InflateException
            Caused by: java.lang.reflect.InvocationTargetException at EmailActivityTest.java:73
                Caused by: java.lang.IllegalStateException at EmailActivityTest.java:73
```

**Comment by SUPERCILEX** [comment]
@samtstern Oh lol, when I restarted my build the tests passed. Maybe also clear the Travis cache?

**Comment by samtstern** [comment]
@SUPERCILEX good call!

**Comment by SUPERCILEX** [comment]
Sweet!

**Pull request merged**
