### PR TITLE
Remove custom test runner, update robolectric

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
Two test are still failing on my machine:

```
com.firebase.ui.auth.ui.email.RegisterEmailActivityTest > testSignUpButton_successfulRegistrationShouldContinueToSaveCredentials FAILED
    junit.framework.ComparisonFailure: expected:<test@example.com> but was:<null>
        at junit.framework.Assert.assertEquals(Assert.java:100)
        at junit.framework.Assert.assertEquals(Assert.java:107)
        at com.firebase.ui.auth.testhelpers.TestHelper.verifySmartLockSave(TestHelper.java:90)
        at com.firebase.ui.auth.testhelpers.TestHelper.verifySmartLockSave(TestHelper.java:73)
        at com.firebase.ui.auth.ui.email.RegisterEmailActivityTest.testSignUpButton_successfulRegistrationShouldContinueToSaveCredentials(RegisterEmailActivityTest.java:134)

com.firebase.ui.auth.ui.email.WelcomeBackPasswordPromptTest > testSignInButton_signsInAndSavesCredentials FAILED
    junit.framework.ComparisonFailure: expected:<test@example.com> but was:<null>
        at junit.framework.Assert.assertEquals(Assert.java:100)
        at junit.framework.Assert.assertEquals(Assert.java:107)
        at com.firebase.ui.auth.testhelpers.TestHelper.verifySmartLockSave(TestHelper.java:90)
        at com.firebase.ui.auth.testhelpers.TestHelper.verifySmartLockSave(TestHelper.java:73)
        at com.firebase.ui.auth.ui.email.WelcomeBackPasswordPromptTest.testSignInButton_signsInAndSavesCredentials(WelcomeBackPasswordPromptTest.java:117)
```

Interestingly the verify password check passes if I comment out the email check, so the email seems to be getting lost in the shuffle.

**Comment by samtstern** [comment]
Ok Travis confirms the failure as well.

**Comment by samtstern** [comment]
I think I got it ...

**Comment by samtstern** [comment]
Honestly I am not sure *why* I had to do some of the things I did, but one thing I know now is that bad things happen when you intersect mocks + static fields + robolectric.

**Comment by SUPERCILEX** [comment]
@samtstern Nice! 😄

**Pull request merged**
