### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RishabhTayal**
Hey there! So you want to contribute to FirebaseUI? Before you file this pull request, follow these steps:

  * Read [the contribution guidelines](CONTRIBUTING.md).
  * Run `./gradlew check` to ensure the Travis build passes.
  * If this has been discussed in an issue, make sure to mention the issue number here.  If not, go file an issue about this to make sure this is a desirable change.
  * If this is a new feature please co-ordinate with someone on [FirebaseUI-iOS](https://github.com/firebase/firebaseui-ios) to make sure that we can implement this on both platforms and maintain feature parity.

### CODE REVIEW

**Comment by TheCraftKid** [comment]
What is the reasoning behind this? FirebaseUI is on version 3.0.0, and this would likely break much of the library.
Is there a specific issue that made you ran into using newer versions of the library? If so, we can address it in a separate issue, but, for now, I don't see any reason why this change is necessary.

**Comment by samtstern** [comment]
I think this was a mistake, closing this PR.

**Comment by RishabhTayal** [comment]
This was not a mistake I opened this issue because the latest version of firebase-ui-auth library (3.0.0) is not working for me. I get following errors.

screenshot 2017-10-23 12 53 01

**Comment by samtstern** [comment]
Add the following your your app:

```groovy
repositories {
  maven {
    url "https://maven.google.com"
  }
}
```

**Pull request closed without merging**
