### PR TITLE
Have FirebaseArray accessible from subclasses

### PR DESCRIPTION
**Pull request by gufux**
Problem:
Currently, I think, It's not possible to remove items from the FirebaseListAdapter without removing it also on firebase db. 

Proposal:
I think (not sure) that having access directly to FirebaseArray would allow to create in the subclass custom adapter a method to remove items **only** on the adpater and not in db.

### CODE REVIEW

**Comment by gufux** [comment]
I signed it

**Comment by gufux** [comment]
I signed it

2016-06-29 18:15 GMT+02:00 googlebot <notifications@github.com>:

**Comment by puf** [comment]
Thanks for the PR. We had some good reasons behind not making the FirebaseArray accessible to sub-classes. 

Can you open an issue (that's in general recommended before opening a PR) and give some more examples of how you'd use the array in your subclasses?

**Comment by gufux** [comment]
Hi @puf 
I created the issue  [FirebaseArray in FirebaseListAdapter is not accessible from subclasses #206 ](https://github.com/firebase/FirebaseUI-Android/issues/206)

**Pull request closed without merging**
