### PR TITLE
Update style guide

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@samtstern While working on #711 the auto formatting was doing everything alphabetically which makes no sense with `ConstraintLayout` since `constraintBottom_...` would end up first and `constraintTop_...` would end up last. This PR updates the style guide so that everything is ordered the following way (including `android:layout...` and `android:padding...`):
1. left
1. right
1. top
1. bottom

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Oh and I also made the style guide add a space to the end of a tag since that seems to be the convention.

**Comment by samtstern** [comment]
Thanks for this!  Just FYI I want to leave this until after version 2.0 since it touches a lot of files and is just cosmetic.

**Comment by SUPERCILEX** [comment]
@samtstern yup, makes sense!

**Comment by SUPERCILEX** [comment]
@samtstern Ok, merged from master!

**Comment by samtstern** [comment]
Gonna merge this one into `master` since it has no functional changes.

**Pull request merged**
