### PR TITLE
Add small troubleshooting for importing sample app

### PR DESCRIPTION
**Pull request by leonjoosse**
I would like to clarify this issue in the README: #1349

### CODE REVIEW

**Comment by leonjoosse** [comment]
I signed it!

**Comment by samtstern** [comment]
@leonjoosse thanks for this clarification!  LGTM, @SUPERCILEX wdyt?

**Comment by SUPERCILEX** [comment]
@samtstern This is kinda Studio's fault, but I don't see why not. 😃

**Comment by trigal2012** [comment]
I'm new to Android and Firebase and I'm trying to use this project. I clone the entire project locally, then opened AS, selected import, then I chose "import project from external model", clicked on Next. The form is then looking for  the "Gradle Home". "Use local gradle distribution" is selected. What value do I enter here? I've tried pointing it to the "gradle" folder located at "FirebaseUI-android/gradle" but that did not work. I also tried pointing to  "FirebaseUI-android/app". I also removed the .idea folder. any help is appreciated.

**Comment by SUPERCILEX** [comment]
@trigal2012 Yeah, that dialog is annoying. Just select the first option to use the Gradle wrapper and click next. I think AS 3.2 will be able to handle the project better.

**Comment by trigal2012** [comment]
@SUPERCILEX thanks for the quick response. looks like I may have another issue because the option you mentioned is grayed out. I'll dig around. Thanks!

**Pull request merged**
