### PR TITLE
Version 4.0

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
Looks like some of my "squash and merge" attempts didn't take.  So this release is going to have an unfortunately messy commit history.

Oh well!

**Comment by samtstern** [comment]
cc @SUPERCILEX @lsirac

**Comment by SUPERCILEX** [comment]
We should also remove the unused resources... I could do that later tonight if needed. 😊

**Comment by samtstern** [comment]
@SUPERCILEX ah good call, I can do that.

**Comment by samtstern** [comment]
I am going to get rid of some of these shitty commits

**Pull request merged**
