### PR TITLE
Fix overlapping view and padding issues

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@lsirac once the diff becomes sane, I'd recommend taking a look at this one since it fixes issues with the ToS. Here's the simplest tip to learn out of this one: always test your layouts in the smallest possible split screen version of FUI.

@samtstern built on top of #1253 because that one fixes similar issues to deal with the progress bars in the phone layouts.

PS: here's what I'm talking about, not so pretty 😭:
screenshot_20180528-203906
screenshot_20180528-203928

### CODE REVIEW

**Comment by lsirac** [comment]
:sob: Thanks Alex!

**Comment by samtstern** [comment]
@SUPERCILEX because this was based on #1253 it has to move to the `4.1.0` milestone.

**Comment by SUPERCILEX** [comment]
@samtstern Any objections to merging?

**Comment by samtstern** [comment]
@SUPERCILEX nope I had just forgotten, thanks!

**Pull request merged**
