### PR TITLE
Merge master into 2.0 dev

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@samtstern Any chance you can merge master into dev so we can take advantage of the new gradle wrapper and prettier starter activity? I know you prefer to do this from the CLI, but I wasn't sure where to put this request so I created a PR for it anyway. Thanks!

### CODE REVIEW

**Comment by samtstern** [comment]
Will do it from the CLI

**Comment by SUPERCILEX** [comment]
Awesome, thanks!

**Comment by samtstern** [comment]
Done!  Github even knew what I was up to and marked this as merged.

**Comment by SUPERCILEX** [comment]
Ooooh, fancy!

**Pull request merged**
