### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by danielpassos**
Related to https://github.com/firebase/FirebaseUI-Android/issues/77

### CODE REVIEW

**Comment by andresgalante** [comment]
Portuguese look ok 
👍

**Comment by Aliihia** [comment]
Free

**Comment by Aliihia** [comment]
L

**Comment by samtstern** [comment]
Hey everyone, I have decided to close translation pull requests.  They've been sitting around for a while and the silent, infinitely-open PR is not fair to you nor is it useful to us.

Eventually, we will get official translations for FirebaseUI for the major languages that Firebase supports.  When we go through that process, I will definitely provide the contents of this Pull Request as suggestions to the translators (there is a place in the system for that).

Thank you for taking the time to contribute!  We do appreciate it, even if we sometimes fail to demonstrate our appreciation.

**Pull request closed without merging**
