### PR TITLE
Reformat .travis.yml

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Looks like #1152 got messed up somehow.

### CODE REVIEW

**Comment by samtstern** [comment]
@SUPERCILEX I **do** like your style better but it actually got into the current state because I used the `travis` command line tool to add those secure env vars.  So not sure what we should go with.

**Comment by SUPERCILEX** [comment]
Oh, huh, I think it's just a bug with the tool since their own docs use the [prettier styling](https://docs.travis-ci.com/user/environment-variables#Defining-encrypted-variables-in-.travis.yml).

**Comment by SUPERCILEX** [comment]
Yeah, even the quote stuff [isn't a thing](https://docs.travis-ci.com/user/languages/android#Caching). 🤷‍♂️

**Comment by samtstern** [comment]
Screw it!  We're human beings and we won't be bossed around by machines.

**Comment by SUPERCILEX** [comment]
Haha, that's the attitude! 😁

**Pull request merged**
